// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Models;

#nullable disable

namespace ProductsApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241016230714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ProductsApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            IsActive = true,
                            Price = 9500m,
                            ProductName = "Iphone 19"
                        },
                        new
                        {
                            ProductId = 2,
                            IsActive = true,
                            Price = 10500m,
                            ProductName = "Iphone 20"
                        },
                        new
                        {
                            ProductId = 3,
                            IsActive = true,
                            Price = 11500m,
                            ProductName = "Iphone 21"
                        },
                        new
                        {
                            ProductId = 4,
                            IsActive = true,
                            Price = 12500m,
                            ProductName = "Iphone 22"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
